CREATE DATABASE customer_behavior;
USE customer_behavior;
select * from customer_data limit 20;

-- questions:
-- 1) total revenue generated by male vs female customers?
-- select gender column,  Calculate total spending by sum of purchase_amount
SELECT gender , SUM(purchase_amount) as revenue 
FROM customer_data
group by gender;  -- combine same gender group

-- 2) which customer used a discount but still spent more than  the average purchase amount
SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)  # this will find the average of whole purchase amount
    FROM customer_data
);

-- 3) which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) as "AVERAGE PRODUCT RATING"
FROM customer_data
GROUP BY item_purchased 
ORDER BY avg(review_rating) DESC  # sort it from highest to lowest rating
LIMIT 5;

-- 4) comapre the average purchase amounts between express and standard shipping
SELECT shipping_type,
ROUND(AVG(purchase_amount))
FROM customer_data
WHERE shipping_type IN ('Standard' , 'Express') # we use IN bcz we have to find the avg of standard and express only
GROUP BY shipping_type;

-- 5) do subscribed customer spend more? compare average spend and total revenue between subscribers and non subscribers
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount)) as avg_spend,
ROUND(SUM(purchase_amount)) as total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- 6) which 5 products have the highest percentage of purchases with dicount applied 
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /COUNT(*) * 100,2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7) segment customers into new, Returning and loyal based on their total number of previous purchases, and show the count of each segment
# questions means divide the customers according to there previous customer based on theses three and count the total customers in each groups
WITH customer_type AS(       # making temporary table
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment #new column
FROM customer_data
)
SELECT customer_segment, count(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- 8) what are the top 3 most purchased products within each category?
WITH item_counts AS(   # new temporary table
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(     # ROW NUMBER WILL GIVE THE NUMBERING
PARTITION BY category   #treat each category different
ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_data
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- 9) are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10) what is the total revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC